# This analysis_options.yaml provides a comprehensive set of lint rules for Flutter projects

include: package:flutter_lints/flutter.yaml

#formatter:
#  page_width: 130
linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_double_quotes: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    use_colored_box: true
    use_full_hex_values_for_flutter_colors: true
    use_named_constants: true

    # Import rules that actually exist
    avoid_relative_lib_imports: true
    directives_ordering: true            # This one sorts imports
    implementation_imports: false
    prefer_relative_imports: false
    always_use_package_imports: true

    always_declare_return_types: true
    avoid_empty_else: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    empty_catches: true

    # Performance
    avoid_unnecessary_containers: true
    use_build_context_synchronously: true
    avoid_slow_async_io: true

    # Best Practices
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    avoid_function_literals_in_foreach_calls: true

    # Debug
    avoid_print: true  # Enabled for development, consider true for production

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_required_param: error
    missing_return: error
    todo: info
    avoid_relative_lib_imports: error    # Change from warning to error
    invalid_use_of_visible_for_testing_member: error



  exclude:
    - "**/*.g.dart"
    - "lib/gen/**"
    - "dev/**"
