name: basic_project_template
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # localization
  easy_localization: ^3.0.7
  # state management
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  bloc_concurrency: ^0.3.0

  path_provider: ^2.1.5
  # dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0
  # assets management
  flutter_gen: ^5.9.0
  # svg and image
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  ionicons: ^0.2.2
  # navigation
  auto_route: ^9.3.0+1
  # logger
  logger: ^2.5.0

  # storage
  sqflite: ^2.4.1
  shared_preferences: ^2.5.1
  flutter_secure_storage: ^9.2.4

  # helping hand
  json_annotation: ^4.9.0
  collection: 1.19.0
  equatable: ^2.0.7
  package_info_plus: ^8.2.0
  path: 1.9.0
  dropdown_button2: ^2.3.9
  country_code_picker: ^3.2.0
  extensions_plus: ^1.3.0

dependency_overrides:
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.9.0
  injectable_generator: ^2.7.0
  auto_route_generator: ^9.3.1
  json_serializable: ^6.9.3

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    # localization
    - assets/translations/
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
